
export const glossaryTerms: Record<string, string> = {
  "Abstração": "Ato de ignorar detalhes irrelevantes para focar nos aspectos essenciais de um problema ou sistema.",
  "Scope creep": "Aumento não planejado e descontrolado do escopo do projeto, geralmente causado por falta de definição clara ou gestão de mudanças.",
  "Gold plating": "Prática de adicionar funcionalidades ou refinamentos que não foram solicitados e não trazem valor claro, desperdiçando recursos.",
  "Viés de confirmação": "Tendência psicológica de favorecer informações que confirmam crenças ou hipóteses pré-existentes.",
  "Elicitação": "Processo de descobrir, extrair e definir requisitos a partir das necessidades dos stakeholders.",
  "Protótipo": "Versão preliminar de um produto ou sistema, usada para testar conceitos e validar requisitos antes do desenvolvimento final.",
  "User Story": "Descrição curta e simples de uma funcionalidade do ponto de vista do usuário (Quem, O quê, Por quê).",
  "Critérios de aceitação": "Conjunto de condições que uma User Story deve satisfazer para ser considerada pronta e aceita.",
  "SMART": "Acrônimo para objetivos: Específicos (Specific), Mensuráveis (Measurable), Atingíveis (Achievable), Relevantes (Relevant) e Temporais (Time-bound).",
  "Gherkin": "Linguagem estruturada (Dado/Quando/Então) usada para escrever cenários de teste e especificações em BDD.",
  "TDD": "Test-Driven Development (Desenvolvimento Guiado por Testes). Prática de escrever testes unitários antes do código.",
  "ATDD": "Acceptance Test-Driven Development. Foca na definição de testes de aceitação antes da implementação.",
  "BDD": "Behavior-Driven Development. Foca no comportamento do sistema e na colaboração entre devs, QA e negócios.",
  "Erro": "Ação humana equivocada (ex: entendimento errado) que dá origem a um defeito.",
  "Defeito": "Imperfeição no artefato (código ou documento), também conhecido como Bug.",
  "Falha": "Comportamento inesperado ou incorreto do sistema durante sua execução.",
  "Verificação": "Processo de avaliar se o produto foi construído corretamente (conforme especificações).",
  "Validação": "Processo de avaliar se o produto certo foi construído (atende às necessidades do usuário).",
  "Shift-Left": "Prática de mover as atividades de teste para o início do ciclo de desenvolvimento.",
  "5 Porquês": "Técnica de resolução de problemas que consiste em perguntar 'Por quê?' repetidamente para encontrar a causa raiz.",
  "Ishikawa": "Diagrama de Espinha de Peixe. Ferramenta visual para organizar causas de um problema em categorias.",
  "Brainstorming": "Técnica de geração de ideias em grupo, focada em quantidade e livre de julgamentos iniciais.",
  "SCAMPER": "Técnica de criatividade que usa verbos (Substituir, Combinar, Adaptar, etc.) para gerar novas ideias.",
  "Modelo RED": "Recognize, Evaluate, Decide. Modelo de pensamento crítico para tomada de decisão.",
  "Upstream": "Fase de descoberta e definição de requisitos, antes do desenvolvimento (Downstream).",
  "Downstream": "Fase de entrega e desenvolvimento, onde os requisitos definidos no Upstream são construídos.",
  "Definition of Ready": "DoR. Lista de critérios que uma história deve cumprir para estar pronta para entrar em desenvolvimento.",
  "Definition of Done": "DoD. Lista de critérios que uma história deve cumprir para ser considerada finalizada."
};
